---
- name: server
  hosts: "*"

  become: yes
  gather_facts: no
  vars:
      git_repo_url: https://github.com/jaydto/rabbitmq.git
      # repo_path: 
  tasks:
    - name:
      apt:
        name: nginx
        state: present
    - name: clone a repository
      git:
        repo: https://github.com/jaydto/rabbitmq.git
        # dest: 
        accept_host_key: yes

    - name: Installing nodejs
      apt: 
        name: nodejs 
        update_cache: yes
    - name: Installing npm
      apt: 
        name: npm 
        update_cache: yes
    - name: Installing dependencies
      command: npm install
    - name: Building
      command: npm run build
    - name: Installing web server
      command: npm install serve
    - name: python installation
      pip:
        requirements: ../requirements.txt
    - name: run server
      command: python3 ../../server/final_server.py

